apiVersion: apps/v1
kind: Deployment
metadata:
  name: origin-api
  # labels:
  #   customer: myself
spec:
  selector:
    matchLabels:
      app: origin-api
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: origin-api
    spec:
      containers:
      - image: gcr.io/$PROJECT_ID/hello-cloudbuild:latest
        name: origin-api-ctr
        ports:
        - containerPort: 5500
        # resources:
        #   requests:
        #     cpu: 0.3
        #   limits: 
        #     cpu: 0.5
        env:
          - name: ORIGIN_DB_HOST
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: db-host
          - name: ORIGIN_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: db-username
          - name: ORIGIN_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: db-password
          - name: ORIGIN_DB_SCHEMA
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: db-schema

---
apiVersion: v1
kind: Service
metadata:
  name: origin-api-svc
  labels:
    app: origin-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5500
  selector:
    app: origin-api

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: origin-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: origin-api
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70